#pragma once

//枚举模型渲染层级类型
enum EMeshRenderLayerType 
{
	RENDERLAYER_OPAQUE = 0,//不透明
	RENDERLAYER_TRANSPARENT,//透明
	RENDERLAYER_ALPHATEST,//Alpha测试
	RENDERLAYER_BACKGROUND,//背景模式

	RENDERLAYER_OPAQUE_REFLECTOR = 4,//不透明的反射层
};